#ifndef GXOS_CREATE_MEMORY_RESOURCE_NOTIFICATION_H
#define GXOS_CREATE_MEMORY_RESOURCE_NOTIFICATION_H

#include "scheduler_foundation.h"

#define GXOS_CREATE_MEMORY_RESOURCE_NOTIFICATION_ERROR_INVALID_PARAMETER 87U
#define GXOS_CREATE_MEMORY_RESOURCE_NOTIFICATION_ERROR_NOT_ENOUGH_MEMORY 8U

#define GXOS_MEMORY_RESOURCE_NOTIFICATION_LOW 0U
#define GXOS_MEMORY_RESOURCE_NOTIFICATION_HIGH 1U

typedef struct {
    GXOS_SCHEDULER *scheduler;
} GXOS_CREATE_MEMORY_RESOURCE_NOTIFICATION_CONTEXT;

GXOS_SCHEDULER_HANDLE GXOS_SCHEDULER_MS_ABI
gxos_create_memory_resource_notification_contract(
    GXOS_CREATE_MEMORY_RESOURCE_NOTIFICATION_CONTEXT *context,
    uint32_t notification_type);

#endif
