#ifndef GXOS_MANAGED_KERNEL_DIAGNOSTIC_RESOURCE_H
#define GXOS_MANAGED_KERNEL_DIAGNOSTIC_RESOURCE_H

#include <stdint.h>

#include "managed_kernel_device_resources.h"

typedef enum {
    GXOS_DIAGNOSTIC_UART_SOURCE_NONE = 0,
    GXOS_DIAGNOSTIC_UART_SOURCE_QEMU_PLATFORM = 1,
    GXOS_DIAGNOSTIC_UART_SOURCE_BOARD_DESCRIPTOR = 2,
    GXOS_DIAGNOSTIC_UART_SOURCE_FIRMWARE_DESCRIPTOR = 3
} GXOS_DIAGNOSTIC_UART_RESOURCE_SOURCE;

typedef enum {
    GXOS_DIAGNOSTIC_UART_BACKEND_UNSUPPORTED = 0,
    GXOS_DIAGNOSTIC_UART_BACKEND_IO_16550 = 1
} GXOS_DIAGNOSTIC_UART_BACKEND;

#define GXOS_DIAGNOSTIC_UART_OWNERSHIP_EXCLUSIVE 0x00000001U
#define GXOS_DIAGNOSTIC_UART_OWNERSHIP_DIAGNOSTIC_ONLY 0x00000002U
#define GXOS_DIAGNOSTIC_UART_REGISTER_SPAN_16550 8U
#define GXOS_DIAGNOSTIC_UART_IRQ_COUNT 16U

typedef struct {
    uint32_t present;
    uint32_t enabled;
    uint32_t source;
    uint32_t backend;
    uint32_t ownership_flags;
    uint16_t io_base;
    uint16_t register_span;
    uint8_t irq;
    uint8_t reserved[3];
} GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESOURCE;

typedef enum {
    GXOS_DIAGNOSTIC_RESOURCE_REASON_NONE = 0,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_NO_RESOURCE,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_INVALID_RESOURCE,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_POLICY_DISABLED,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_IO_CONFLICT,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_IRQ_CONFLICT,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_RESERVATION_FAILED,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_UART_INIT_FAILED,
    GXOS_DIAGNOSTIC_RESOURCE_REASON_IRQ_REGISTRATION_FAILED
} GXOS_DIAGNOSTIC_RESOURCE_DISABLE_REASON;

typedef enum {
    GXOS_DIAGNOSTIC_RESOURCE_QUERY_UNAVAILABLE = 0,
    GXOS_DIAGNOSTIC_RESOURCE_QUERY_VALID = 1,
    GXOS_DIAGNOSTIC_RESOURCE_QUERY_INVALID = 2
} GXOS_DIAGNOSTIC_RESOURCE_QUERY_RESULT;

typedef struct {
    uint32_t owned;
    uint32_t resource_type;
    uint32_t owner;
    uint16_t io_base;
    uint16_t register_span;
    uint8_t irq;
    uint8_t reserved[3];
} GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESERVATION;

typedef int (*GXOS_DIAGNOSTIC_UART_STAGE)(
    void *context, const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESOURCE *resource);
typedef void (*GXOS_DIAGNOSTIC_UART_ROLLBACK_STAGE)(
    void *context, const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESOURCE *resource);

typedef struct {
    GXOS_DIAGNOSTIC_UART_STAGE initialize_uart;
    GXOS_DIAGNOSTIC_UART_STAGE register_irq;
    GXOS_DIAGNOSTIC_UART_ROLLBACK_STAGE unregister_irq;
    GXOS_DIAGNOSTIC_UART_ROLLBACK_STAGE stop_uart;
} GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_OPERATIONS;

typedef enum {
    GXOS_DIAGNOSTIC_RESOURCE_ACTIVATION_DISABLED = 0,
    GXOS_DIAGNOSTIC_RESOURCE_ACTIVATION_ENABLED = 1
} GXOS_DIAGNOSTIC_RESOURCE_ACTIVATION_RESULT;

GXOS_DIAGNOSTIC_RESOURCE_QUERY_RESULT
gxos_managed_kernel_diagnostic_uart_validate(
    const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESOURCE *resource);

GXOS_DIAGNOSTIC_RESOURCE_ACTIVATION_RESULT
gxos_managed_kernel_diagnostic_uart_activate(
    const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESOURCE *resource,
    uint32_t diagnostic_policy_allowed,
    const GX_MANAGED_KERNEL_DEVICE_RESOURCE_V1 *registered_resources,
    uint32_t registered_resource_count,
    uint32_t exclusive_irq_mask,
    GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESERVATION *reservation,
    const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_OPERATIONS *operations,
    void *operation_context,
    GXOS_DIAGNOSTIC_RESOURCE_DISABLE_REASON *reason_out);

void gxos_managed_kernel_diagnostic_uart_release(
    const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESOURCE *resource,
    GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_RESERVATION *reservation,
    const GXOS_MANAGED_KERNEL_DIAGNOSTIC_UART_OPERATIONS *operations,
    void *operation_context);

#endif
