#ifndef GXOS_PLATFORM_ENVIRONMENT_H
#define GXOS_PLATFORM_ENVIRONMENT_H

#include <stdint.h>

#if defined(__x86_64__)
#define GXOS_ENVIRONMENT_MS_ABI __attribute__((ms_abi))
#else
#define GXOS_ENVIRONMENT_MS_ABI
#endif

typedef uint16_t GXOS_ENVIRONMENT_WCHAR;
typedef uint32_t GXOS_ENVIRONMENT_DWORD;

#define GXOS_ENVIRONMENT_ERROR_SUCCESS ((GXOS_ENVIRONMENT_DWORD)0)
#define GXOS_ENVIRONMENT_ERROR_INVALID_PARAMETER ((GXOS_ENVIRONMENT_DWORD)87)
#define GXOS_ENVIRONMENT_ERROR_ENVVAR_NOT_FOUND ((GXOS_ENVIRONMENT_DWORD)203)
#define GXOS_ENVIRONMENT_MAX_NAME_CHARS ((uint32_t)32767)
#define GXOS_ENVIRONMENT_MAX_MEMORY_REGIONS ((uint32_t)16)

typedef enum {
    GXOS_ENVIRONMENT_STATUS_OK = 0,
    GXOS_ENVIRONMENT_STATUS_INVALID_OUTPUT,
    GXOS_ENVIRONMENT_STATUS_INVALID_CONTEXT,
    GXOS_ENVIRONMENT_STATUS_INVALID_NAME,
    GXOS_ENVIRONMENT_STATUS_UNTERMINATED_NAME,
    GXOS_ENVIRONMENT_STATUS_INVALID_BUFFER,
    GXOS_ENVIRONMENT_STATUS_INVALID_TABLE,
    GXOS_ENVIRONMENT_STATUS_SIZE_OVERFLOW
} GXOS_ENVIRONMENT_STATUS;

typedef struct {
    uintptr_t begin;
    uintptr_t end;
    uint32_t readable;
    uint32_t writable;
} GXOS_ENVIRONMENT_MEMORY_REGION;

typedef struct {
    uint32_t region_count;
    const GXOS_ENVIRONMENT_MEMORY_REGION *regions;
} GXOS_ENVIRONMENT_MEMORY_CONTEXT;

typedef struct {
    const GXOS_ENVIRONMENT_WCHAR *name;
    uint32_t name_length;
    const GXOS_ENVIRONMENT_WCHAR *value;
    uint32_t value_length;
} GXOS_ENVIRONMENT_ENTRY;

GXOS_ENVIRONMENT_STATUS GXOS_ENVIRONMENT_MS_ABI gxos_get_environment_variable_w_checked(
    const GXOS_ENVIRONMENT_WCHAR *name,
    GXOS_ENVIRONMENT_WCHAR *buffer,
    GXOS_ENVIRONMENT_DWORD buffer_size,
    const GXOS_ENVIRONMENT_ENTRY *entries,
    uint32_t entry_count,
    const GXOS_ENVIRONMENT_MEMORY_CONTEXT *memory,
    GXOS_ENVIRONMENT_DWORD previous_last_error,
    GXOS_ENVIRONMENT_DWORD *return_value,
    GXOS_ENVIRONMENT_DWORD *last_error);

GXOS_ENVIRONMENT_DWORD GXOS_ENVIRONMENT_MS_ABI gxos_get_environment_variable_w_not_found(
    const GXOS_ENVIRONMENT_WCHAR *name,
    GXOS_ENVIRONMENT_WCHAR *buffer,
    GXOS_ENVIRONMENT_DWORD buffer_size,
    GXOS_ENVIRONMENT_DWORD *last_error);

#endif
