using System;

namespace GuideXOS.Net10.ManagedKernel;

/* Deterministic Phase 40 proof.  The response fixture is generated by the
   host runner as a gzip member around this fixed pattern.  The proof checks
   decoded bytes, not the encoded Content-Length, and intentionally pauses at
   the resource-consumer boundary. */
internal sealed class ManagedPhase40ResourceProof
{
    private const int ResourceLength = 16_384;
    private const int PrefixLength = 32;
    private static readonly byte[] ExpectedDigest =
    {
        0x90, 0x38, 0xAC, 0x64, 0xE6, 0x59, 0x33, 0x5C,
        0xCB, 0xFD, 0xD3, 0xF6, 0x84, 0xF3, 0x5A, 0x26,
        0xA2, 0xC9, 0xE5, 0x80, 0xD9, 0xAF, 0x6B, 0x48,
        0x07, 0xAF, 0x3A, 0xDB, 0xE2, 0xC2, 0x57, 0xE3
    };

    private static ReadOnlySpan<byte> Hostname => "www.example.com"u8;
    private static ReadOnlySpan<byte> Path => "/phase40/gzip"u8;
    private static ReadOnlySpan<byte> ContentType => "application/octet-stream"u8;

    private readonly ManagedNetworkService _service;
    private readonly ManagedResourceRequest _resource;
    private readonly ManagedResourceCountConsumer _count = new();
    private readonly ManagedResourceSha256Consumer _hash = new();
    private readonly ManagedResourcePrefixConsumer _prefix = new(new byte[PrefixLength]);
    private readonly ManagedResourceCompositeConsumer _pipeline;
    private bool _dnsLogged;
    private bool _tcpLogged;
    private bool _tlsLogged;
    private bool _requestLogged;
    private bool _applicationLogged;
    private bool _statusLogged;
    private bool _bodyLogged;
    private bool _pauseObserved;
    private int _peakEncodedBuffer;
    private int _peakDecodedBuffer;

    internal ManagedPhase40ResourceProof(ManagedNetworkService service)
    {
        _service = service;
        ManagedSecureRandom random = new(new FixedEntropy(CreateEntropy()));
        _pipeline = new(_count, _hash, _prefix);
        _resource = new(service, ManagedTls12Phase31Fixtures.Root,
                        new ManagedX509UtcTime(2028, 1, 1, 0, 0, 0), random,
                        ManagedHttpLimits.MaximumStreamedBodyLength,
                        compactTlsProfile: false,
                        maximumDecodedResourceLength: ManagedContentEncodingLimits.MaximumDecodedResourceLength);
    }

    internal bool TryRun()
    {
        if (!_service.GetStatus().DhcpBound || !_service.GetStatus().Configured ||
            !KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_READY\r\n"u8) ||
            _resource.BeginGet(Hostname, Path, _pipeline) != NetworkOperationResult.Started ||
            !KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_STARTED\r\n"u8))
            return false;

        if (!KernelLog.Write(
                "GXOS_NET10:MANAGED_HTTPS_PHASE40_REQUEST_STARTED\r\n"u8))
            return false;

        for (int poll = 0; poll != 65_536; ++poll)
        {
            NetworkOperationResult result = _resource.Poll();
            ManagedResourceProgressSnapshot progress = _resource.Progress;
            if (progress.PeakBufferedBytes > _peakEncodedBuffer)
                _peakEncodedBuffer = progress.PeakBufferedBytes;
            if (progress.PeakDecodedOutputBytes > _peakDecodedBuffer)
                _peakDecodedBuffer = progress.PeakDecodedOutputBytes;
            if (!ObserveTransport(progress)) return false;
            if (result == NetworkOperationResult.Failed ||
                _resource.State == ManagedResourceState.Failed)
                return WriteFailure(progress);

            if (!_pauseObserved && progress.DecodedBytesConsumed != 0)
            {
                if (_resource.Pause() != NetworkOperationResult.Success)
                    return false;
                ManagedResourceProgressSnapshot paused = _resource.Progress;
                for (int stable = 0; stable != 4; ++stable)
                {
                    if (_resource.Poll() != NetworkOperationResult.Success)
                        return false;
                    ManagedResourceProgressSnapshot current = _resource.Progress;
                    if (current.State != ManagedResourceState.Paused ||
                        current.EncodedBytesReceived != paused.EncodedBytesReceived ||
                        current.EncodedBytesConsumed != paused.EncodedBytesConsumed ||
                        current.DecodedBytesProduced != paused.DecodedBytesProduced ||
                        current.DecodedBytesConsumed != paused.DecodedBytesConsumed ||
                        current.BufferedDecodedBytes != paused.BufferedDecodedBytes)
                        return false;
                }
                _pauseObserved = true;
                if (_resource.Resume() != NetworkOperationResult.Success ||
                    !KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_PAUSED\r\n"u8) ||
                    !KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_PAUSED_POLLS=0x"u8, 4) ||
                    !KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_RESUMED\r\n"u8))
                    return false;
            }
            if (_resource.State == ManagedResourceState.Completed)
                return FinishSuccess();
        }
        return false;
    }

    private bool ObserveTransport(ManagedResourceProgressSnapshot progress)
    {
        if (!_dnsLogged && _resource.ResolvedAddress.IsUsable)
        {
            _dnsLogged = true;
            if (!KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_DNS_SUCCESS\r\n"u8)) return false;
        }
        if (!_tcpLogged && _resource.TcpState == NetworkTcpState.Established)
        {
            _tcpLogged = true;
            if (!KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_TCP_CONNECTED\r\n"u8)) return false;
        }
        if (!_tlsLogged && _resource.TlsAuthenticated)
        {
            _tlsLogged = true;
            if (!KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_TLS_HANDSHAKE_AUTHENTICATED\r\n"u8)) return false;
        }
        if (!_requestLogged && _resource.RequestSent)
        {
            _requestLogged = true;
            if (!KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_HTTP_REQUEST_ENCRYPTED_SENT\r\n"u8)) return false;
        }
        if (!_applicationLogged && _resource.ApplicationDataReceived)
        {
            _applicationLogged = true;
            if (!KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_TLS_APPLICATION_DATA_AUTHENTICATED_DECRYPTED\r\n"u8)) return false;
        }
        if (!_statusLogged && progress.StatusCode != 0)
        {
            _statusLogged = true;
            if (!KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_HTTP_STATUS_PARSED=0x"u8,
                                       (ulong)progress.StatusCode)) return false;
        }
        if (!_bodyLogged && progress.DecodedBytesConsumed != 0)
        {
            _bodyLogged = true;
            if (!KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_BODY_RECEIVED\r\n"u8)) return false;
        }
        return true;
    }

    private bool FinishSuccess()
    {
        ManagedResourceProgressSnapshot progress = _resource.Progress;
        Span<byte> digest = stackalloc byte[ManagedResourceSha256Consumer.DigestSize];
        Span<byte> prefix = stackalloc byte[PrefixLength];
        Span<byte> contentType = stackalloc byte[ManagedHttpLimits.MaximumContentTypeLength];
        Span<byte> contentEncoding = stackalloc byte[ManagedHttpLimits.MaximumContentEncodingLength];
        if (!_pauseObserved || progress.StatusCode != 200 ||
            progress.TransferMode != ManagedHttpFramingMode.ContentLength ||
            !progress.HasKnownTotalLength || progress.TotalEntityLength <= 0 ||
            progress.TotalEntityLength > ManagedHttpLimits.MaximumStreamedBodyLength ||
            progress.EncodedBytesReceived != progress.TotalEntityLength ||
            progress.EncodedBytesConsumed != progress.TotalEntityLength ||
            progress.DecodedBytesProduced != ResourceLength ||
            progress.DecodedBytesConsumed != ResourceLength ||
            progress.ResourceBytesProcessed != ResourceLength ||
            progress.BufferedDecodedBytes != 0 || progress.PauseCount != 1 ||
            progress.ResumeCount != 1 || progress.DecoderPauseCount != 0 ||
            progress.DecoderResumeCount != 0 || !progress.CrcValidated ||
            !progress.IsizeValidated ||
            !_resource.TryCopyContentType(contentType, out int contentTypeLength) ||
            !contentType[..contentTypeLength].SequenceEqual(ContentType) ||
            !_resource.TryCopyContentEncoding(contentEncoding, out int encodingLength) ||
            !contentEncoding[..encodingLength].SequenceEqual("gzip"u8) ||
            !_hash.TryCopyDigest(digest) || !digest.SequenceEqual(ExpectedDigest) ||
            !_prefix.TryCopyPrefix(prefix, out int prefixLength) ||
            prefixLength != PrefixLength || !CheckPattern(prefix))
            return false;

        return KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_STATUS=0x"u8, (ulong)progress.StatusCode) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_TRANSFER_MODE=0x"u8, (ulong)progress.TransferMode) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_TOTAL_KNOWN=0x"u8, progress.HasKnownTotalLength ? 1UL : 0UL) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_TOTAL_LENGTH=0x"u8, (ulong)progress.TotalEntityLength) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_CONTENT_TYPE_LENGTH=0x"u8, (ulong)contentTypeLength) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_CONTENT_ENCODING_LENGTH=0x"u8, (ulong)encodingLength) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_ENCODED_CONTENT_LENGTH=0x"u8, (ulong)progress.TotalEntityLength) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_ENCODED_BYTES_RECEIVED=0x"u8, (ulong)progress.EncodedBytesReceived) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_ENCODED_BYTES_CONSUMED=0x"u8, (ulong)progress.EncodedBytesConsumed) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODED_BYTES_PRODUCED=0x"u8, (ulong)progress.DecodedBytesProduced) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODED_BYTES_CONSUMED=0x"u8, (ulong)progress.DecodedBytesConsumed) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_SEGMENTS=0x"u8, (ulong)progress.DeliveredSegmentCount) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_PAUSE_COUNT=0x"u8, (ulong)progress.PauseCount) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESUME_COUNT=0x"u8, (ulong)progress.ResumeCount) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODER_STATE=0x"u8, (ulong)progress.DecoderState) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODER_FAILURE=0x"u8, (ulong)progress.DecoderFailureReason) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODER_PAUSE_COUNT=0x"u8, (ulong)progress.DecoderPauseCount) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODER_RESUME_COUNT=0x"u8, (ulong)progress.DecoderResumeCount) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_BUFFERED_DECODED_BYTES=0x"u8, (ulong)progress.BufferedDecodedBytes) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_PEAK_ENCODED_BUFFER=0x"u8, (ulong)_peakEncodedBuffer) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_PEAK_DECODED_BUFFER=0x"u8, (ulong)_peakDecodedBuffer) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_HISTORY_WINDOW=0x"u8, (ulong)progress.DecoderHistoryWindowSize) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_PREFIX_BYTES=0x"u8, (ulong)prefixLength) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_COMPRESSION_RATIO_NUMERATOR=0x"u8, (ulong)progress.DecodedBytesProduced) &&
               KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_COMPRESSION_RATIO_DENOMINATOR=0x"u8, (ulong)progress.EncodedBytesReceived) &&
               KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_CRC_VALIDATED\r\n"u8) &&
               KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_ISIZE_VALIDATED\r\n"u8) &&
               WriteDigest(digest) &&
               KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_COMPLETE\r\n"u8) &&
               KernelLog.Write("GXOS_NET10:MANAGED_HTTPS_PHASE40_RESOURCE_PASS\r\n"u8);
    }

    private static bool WriteDigest(ReadOnlySpan<byte> digest)
    {
        for (int index = 0; index != digest.Length; index += 4)
        {
            uint word = ((uint)digest[index] << 24) | ((uint)digest[index + 1] << 16) |
                        ((uint)digest[index + 2] << 8) | digest[index + 3];
            if (!KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_SHA256_WORD=0x"u8, word))
                return false;
        }
        return true;
    }

    private bool WriteFailure(ManagedResourceProgressSnapshot progress)
    {
        KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_FAILURE=0x"u8,
                               (ulong)progress.FailureReason);
        KernelLog.WriteHexLine("GXOS_NET10:MANAGED_HTTPS_PHASE40_DECODER_FAILURE=0x"u8,
                               (ulong)progress.DecoderFailureReason);
        return false;
    }

    private static bool CheckPattern(ReadOnlySpan<byte> value)
    {
        for (int index = 0; index != value.Length; ++index)
            if (value[index] != (byte)((index * 31 + 7) & 0xFF)) return false;
        return true;
    }

    private static byte[] CreateEntropy()
    {
        byte[] entropy = new byte[64];
        ManagedTls12Phase31Fixtures.ClientRandom.CopyTo(entropy, 0);
        entropy[63] = 1;
        return entropy;
    }

    private sealed class FixedEntropy : IManagedEntropyProvider
    {
        private readonly byte[] _bytes;
        private int _offset;
        internal FixedEntropy(byte[] bytes) => _bytes = bytes;
        public bool IsAvailable => _bytes.Length != 0;
        public bool TryFill(Span<byte> destination)
        {
            for (int index = 0; index != destination.Length; ++index)
                destination[index] = _bytes[_offset++ % _bytes.Length];
            return true;
        }
    }
}
