[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string]$InputDirectory,
    [Parameter(Mandatory = $true)] [string]$OutputFile
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$inputDirectory = [IO.Path]::GetFullPath($InputDirectory)
$outputFile = [IO.Path]::GetFullPath($OutputFile)
$project = Join-Path $PSScriptRoot 'ReferenceFixtureGenerator.csproj'
$dotnet = Get-Command dotnet -ErrorAction Stop
$sdkDirectory = Join-Path (Split-Path -Parent $dotnet.Source) 'sdk\10.0.400'
$msbuild = Join-Path $sdkDirectory 'MSBuild.dll'
if (-not (Test-Path -LiteralPath $msbuild)) {
    throw "Missing .NET 10.0.400 MSBuild entry point: $msbuild"
}
foreach ($name in @('root.der', 'intermediate.der', 'leaf.der', 'ske-signature.der')) {
    $path = Join-Path $inputDirectory $name
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing fixture input: $path"
    }
}

# The generator is intentionally host-only. It uses System.Security.Cryptography
# to create an independent TLS transcript and AES-GCM reference, while the
# generated bytes are the only artifact copied into the managed-kernel payload.
$parent = Split-Path -Parent $root
Push-Location $parent
try {
    & $dotnet.Source $msbuild $project '/t:Restore' '/p:Configuration=Release' `
        '/p:RestoreIgnoreFailedSources=true' | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "Fixture generator restore failed: $LASTEXITCODE" }
    & $dotnet.Source $msbuild $project '/t:Build' '/p:Configuration=Release' `
        '/p:RestoreIgnoreFailedSources=true' | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "Fixture generator build failed: $LASTEXITCODE" }
    $assembly = Join-Path $PSScriptRoot 'bin\Release\net10.0\ReferenceFixtureGenerator.dll'
    & $dotnet.Source $assembly $inputDirectory $outputFile
    if ($LASTEXITCODE -ne 0) { throw "Fixture generator failed: $LASTEXITCODE" }
} finally {
    Pop-Location
}
Write-Output "PHASE31_FIXTURE_GENERATOR=HOST_ONLY_REFERENCE"
Write-Output "PHASE31_FIXTURE_OUTPUT=$outputFile"
