[CmdletBinding()]
param(
    [string]$SourceDirectory = 'D:\dev\guideXOSServer_NAVIGATOR_IMPROVEMENTS\assets\Fonts\roboto',
    [string]$OutputPath = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $root 'src\ManagedKernel\ManagedPhase48GeneratedFontData.g.cs'
}
$source = [IO.Path]::GetFullPath($SourceDirectory)
$output = [IO.Path]::GetFullPath($OutputPath)
$faces = @(
    @{ Name = 'Roboto9Regular'; File = 'roboto_9pt_regular.png'; Size = 9; Baseline = 12; Ascent = 8; Descent = 4; LineGap = 4 },
    @{ Name = 'Roboto9Bold'; File = 'roboto_9pt_bold.png'; Size = 9; Baseline = 12; Ascent = 8; Descent = 4; LineGap = 4 },
    @{ Name = 'Roboto9Italic'; File = 'roboto_9pt_italic.png'; Size = 9; Baseline = 12; Ascent = 8; Descent = 4; LineGap = 4 },
    @{ Name = 'Roboto9BoldItalic'; File = 'roboto_9pt_bolditalic.png'; Size = 9; Baseline = 12; Ascent = 8; Descent = 4; LineGap = 4 },
    @{ Name = 'Roboto12Regular'; File = 'roboto_12pt_regular.png'; Size = 12; Baseline = 13; Ascent = 9; Descent = 5; LineGap = 4 },
    @{ Name = 'Roboto12Bold'; File = 'roboto_12pt_bold.png'; Size = 12; Baseline = 13; Ascent = 9; Descent = 5; LineGap = 4 },
    @{ Name = 'Roboto12Italic'; File = 'roboto_12pt_italic.png'; Size = 12; Baseline = 13; Ascent = 9; Descent = 5; LineGap = 4 },
    @{ Name = 'Roboto12BoldItalic'; File = 'roboto_12pt_bolditalic.png'; Size = 12; Baseline = 13; Ascent = 9; Descent = 5; LineGap = 4 }
)

function Format-Bytes([byte[]]$bytes) {
    return [Convert]::ToBase64String($bytes)
}

function Format-Metadata($metadata) {
    $lines = [Collections.Generic.List[string]]::new()
    foreach ($item in $metadata) {
        $flag = if ($item.HasPixels) { 1 } else { 0 }
        $format = '        new ManagedPhase48GlyphMetadata({0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}),'
        $lines.Add(($format -f $item.X, $item.Y, $item.Width, $item.Height, $item.Advance, $item.BearingX, $item.BearingY, $flag))
    }
    $lines[$lines.Count - 1] = $lines[$lines.Count - 1].TrimEnd(',')
    return $lines -join "`n"
}

$sourceHashes = [Collections.Generic.List[string]]::new()
$generated = [Text.StringBuilder]::new()
[void]$generated.AppendLine('// <auto-generated />')
[void]$generated.AppendLine('// Generated by tools/Generate-ManagedPhase48FontData.ps1 from the guideXOS Navigator Roboto bitmap atlases.')
[void]$generated.AppendLine('// Guest code consumes only these static alpha bytes; System.Drawing is build-time tooling only.')
[void]$generated.AppendLine('using System;')
[void]$generated.AppendLine()
[void]$generated.AppendLine('namespace GuideXOS.Net10.ManagedKernel;')
[void]$generated.AppendLine()
[void]$generated.AppendLine('internal static class ManagedPhase48GeneratedFontData')
[void]$generated.AppendLine('{')

foreach ($face in $faces) {
    $path = Join-Path $source $face.File
    if (-not (Test-Path -LiteralPath $path)) { throw "Font atlas not found: $path" }
    $hash = (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToUpperInvariant()
    $sourceHashes.Add("$($face.Name)=$hash")
    $bitmap = [Drawing.Bitmap]::new($path)
    try {
        if ($bitmap.Width -ne 260 -or $bitmap.Height -ne 160) {
            throw "Unexpected atlas geometry for ${path}: $($bitmap.Width)x$($bitmap.Height)"
        }
        $alpha = [byte[]]::new($bitmap.Width * $bitmap.Height)
        $metadata = [Collections.Generic.List[object]]::new()
        for ($codePoint = 32; $codePoint -le 126; ++$codePoint) {
            $cell = $codePoint - 32
            $cellX = ($cell % 13) * 20
            $cellY = [int]($cell / 13) * 20
            $left = 20; $top = 20; $right = -1; $bottom = -1
            for ($y = 0; $y -lt 20; ++$y) {
                for ($x = 0; $x -lt 20; ++$x) {
                    $pixel = $bitmap.GetPixel($cellX + $x, $cellY + $y)
                    $value = [byte]$pixel.A
                    $alpha[($cellY + $y) * $bitmap.Width + $cellX + $x] = $value
                    if ($value -ne 0) {
                        if ($x -lt $left) { $left = $x }
                        if ($y -lt $top) { $top = $y }
                        if ($x -gt $right) { $right = $x }
                        if ($y -gt $bottom) { $bottom = $y }
                    }
                }
            }
            if ($right -lt 0) {
                $left = 0; $top = 0; $width = 0; $height = 0
                $advance = if ($face.Size -eq 9) { 4 } else { 5 }
                $bearingX = 0; $bearingY = 0; $hasPixels = $false
            } else {
                $width = $right - $left + 1
                $height = $bottom - $top + 1
                $advance = $width + 1
                $bearingX = $left
                $bearingY = $top - $face.Baseline
                $hasPixels = $true
            }
            $metadata.Add([pscustomobject]@{ X = $cellX; Y = $cellY; Width = $width; Height = $height; Advance = $advance; BearingX = $bearingX; BearingY = $bearingY; HasPixels = $hasPixels; CodePoint = $codePoint })
        }
        $encoded = Format-Bytes $alpha
        [void]$generated.AppendLine(('    internal static readonly byte[] {0}Alpha = Convert.FromBase64String("{1}");' -f $face.Name, $encoded))
        [void]$generated.AppendLine()
        [void]$generated.AppendLine("    internal static readonly ManagedPhase48GlyphMetadata[] $($face.Name)Glyphs = new ManagedPhase48GlyphMetadata[]")
        [void]$generated.AppendLine('    {')
        [void]$generated.AppendLine((Format-Metadata $metadata))
        [void]$generated.AppendLine('    };')
        [void]$generated.AppendLine()
    } finally {
        $bitmap.Dispose()
    }
}

[void]$generated.AppendLine('    internal static readonly string[] SourceHashes = new string[]')
[void]$generated.AppendLine('    {')
foreach ($hash in $sourceHashes) { [void]$generated.AppendLine(('        "{0}",' -f $hash)) }
[void]$generated.AppendLine('    };')
[void]$generated.AppendLine('}')

$parent = Split-Path -Parent $output
New-Item -ItemType Directory -Force -Path $parent | Out-Null
[IO.File]::WriteAllText($output, $generated.ToString(), [Text.UTF8Encoding]::new($false))
Write-Output "GENERATED_MANAGED_PHASE48_FONT_DATA=$output"
Write-Output "MANAGED_PHASE48_FONT_SOURCE_HASHES=$($sourceHashes -join ';')"
